GET http://localhost:5000/users?page=0&limit=10 



###
GET http://localhost:5000/users/100012

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Bally sofyan",
    "email": "sofyan14@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:5000/users/100011
Content-Type: application/json

{
    "name": "Yanz KIllaz",
    "email": "sofyan14@gmail.com",
    "gender": "Male"
}


###
DELETE   http://localhost:5000/users/100010